### ISSUE TITLE
No module named 'base'

### ISSUE THREAD

**Issue by athtareq** [mghasemi/pyProximation#1]
Hello, I'm trying to run some examples listed in https://pyproximation.readthedocs.io/en/latest/collocation.html#

But I run into the error 

```
[/content/pyProximation/pyProximation/measure.py](https://localhost:8080/#) in <module>
----> 1 from base import Foundation
      2 
      3 
      4 class Measure(Foundation):
      5     """

ModuleNotFoundError: No module named 'base'
```

Here's the Colab notebook I used for the installation process https://colab.research.google.com/drive/1jRo7eC_-QThFiKcBq1APltOI7bbhIfJh#scrollTo=bWAc0KqvEkrI

Is there any fix ? Thanks.

**Comment by mghasemi** [comment]
It's been a while since last I touched this package. 
It needs to be updated.
I'll try to update the library and will let you know.

Thank you for using this and raising the issue.

**Comment by athtareq** [comment]
@mghasemi duly noted, thank you very much.

**Comment by mghasemi** [comment]
Could you try the updated version?
It works for the Colab notebook you shared, subject to minor changes on the keys of the 'Appx', which is no longer a list but a dict.

**Comment by athtareq** [comment]
Yes, the notebook is now working. Thank you very much.
